- name: create systemd unit
  ansible.builtin.template:
    src: nomad-systemd.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  notify: systemd_reload
  tags:
    - nomad-config

- name: place nomad env
  ansible.builtin.template:
    src: "nomad-env.j2"
    dest: "{{ nomad_config_path | dirname }}/nomad.env"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0640
  notify: restart nomad services
  tags:
    - nomad-config

- name: place nomad common configuration
  ansible.builtin.template:
    src: "nomad-common.j2"
    dest: "{{ nomad_config_path | dirname }}/nomad.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0640
  notify: restart nomad services
  tags:
    - nomad-config

- name: place nomad agent specific configuration
  ansible.builtin.template:
    src: "nomad-config.j2"
    dest: "{{ nomad_config_path | dirname }}/agent.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0640
  notify: restart nomad services
  tags:
    - nomad-config

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
