- name: "placing Traefik static configs"
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ traefik_config_file }}"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: "0655"
  notify:
    - "restart traefik services"
  loop:
    - "{{ traefik_config }}"
  tags:
    - "traefik-config"

- name: "Put in dynamic routers"
  ansible.builtin.template:
    src: "router.j2"
    dest: "{{ traefik_config_file | dirname }}/configs/{{ item['name'] }}.yaml"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: "0655"
  loop: "{{ proxy_sites['routers'] }}"
  tags:
    - "traefik-config"
