---
# handlers file for consul-install
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen:
    - reload_systemd
    - systemd_reload
    - "restart consul services"
    - "restart consul template services"

- name: restart consul
  ansible.builtin.systemd:
    name: consul.service
    state: restarted
  listen:
    - restart_consul
    - consul_restart
    - "restart consul services"

- name: restart consul-template
  ansible.builtin.systemd:
    name: consul-template.service
    state: restarted
  listen:
    - "restart consul template services"

- name: restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted
