- name: === SYSTEMD SERVICE HANDLERS ===
  block:
    - name: systemd_reload_config
      become: true
      systemd:
        daemon_reload: true

    - name: systemd_restart_vault
      become: true
      systemd:
        name: vault
        state: restarted
  when: ansible_facts['service_mgr'] == 'systemd'
