---
# defaults file for traefik_install
###############
# Traefik Proxy
###############
traefik_config_file: "/etc/traefik/traefik.yaml"
traefik_binary_path: "/opt/bin"

traefik_user: "traefik"
traefik_group: "traefik"

traefik_proxy:
  url: "https://github.com/traefik/traefik/releases/download"
  version: "2.5.4"
  path_unit:
    name: "traefik.path"
    Description: "Watch for config file changes for Traefik Proxy"
    Path: "{{ traefik_config_file }}"
  service_unit:
    name: "traefik.service"
    Description: "Traefik Proxy"
    Documentation: "https://doc.traefik.io/traefik/"
    User: "traefik"
    Group: "traefik"
    Restart: "on-abnormal"
    ExecStart: "{{ traefik_binary_path }} --configfile={{ traefik_config_file }}"
    TimeoutStopSec: "5s"
    LimitNOFILE: "1048576"
    LimitNPROC: "512"
    PrivateTmp: true
    ProtectHome: true
    ProtectSystem: true
    AmbientCapabilities:
      - "CAP_NET_BIND_SERVICE"
    CapabilityBoundingSet:
      - "CAP_NET_BIND_SERVICE"
    NoNewPrivileges: true
    AssertFileIsExecutable:
      - "{{ traefik_binary_path }}"
    ConditionPathExists:
      - "{{ traefik_binary_path }}"
      - "{{ traefik_config_file }}"
    After:
      - "network.target"
      - "network-online.target"
    Wants:
      - "network-online.target"
      - "systemd-networkd-wait-online.service"
    ReadWriteDirectories:
      - "{{ traefik_config_file | dirname }}"
      - "{{ traefik_config_file | dirname }}/logs"
      - "{{ traefik_config_file | dirname }}/certs"
      - "{{ traefik_config_file | dirname }}/configs"
      - "-{{ traefik_config_file | dirname }}/acme"

traefik_config:
  global:
    checkNewVersion: false
    sendAnonymousUsage: false
  pilot:
    dashboard: false
  ping: {}
  api:
    dashboard: true
    debug: true
  log:
    level: "DEBUG"
    format: "json"
    filePath: "{{ traefik_config_file | dirname }}/logs/traefik.log"
  accessLog:
    format: "json"
    filePath: "{{ traefik_config_file | dirname }}/logs/access.log"
    fields:
      names:
        - "StartUTC: drop"
  providers:
    file:
      directory: "{{ traefik_config_file | dirname }}/configs/"
  certificatesResolvers:
    le-prod:
      email: "{{ cf_email }}"
      storage: "{{ traefik_config_file | dirname }}/certs/acme.json"
      keyType: "EC256"
      challenge: "dnsChallenge"
      provider: "cloudflare"
      resolvers:
        - "1.1.1.1:53"
        - "8.8.8.8:53"
  entryPoints:
    kube_api:
      address: ":6443"

    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true

    websecure:
      address: ":443"
