---
# handlers file for vault-install

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen:
    - reload_systemd
    - systemd_reload

- name: restart vault
  ansible.builtin.systemd:
    name: vault.service
    state: restarted
  listen:
    - restart_vault
    - vault_restart
    - "restart vault services"
