- name: create systemd unit
  ansible.builtin.template:
    src: consul-systemd.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  notify: systemd_reload
  tags:
    - consul-config

- name: place consul env
  ansible.builtin.template:
    src: "consul-env.j2"
    dest: "{{ consul_config_path | dirname }}/consul.env"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  notify: restart consul services
  tags:
    - consul-config

- name: place consul common configuration
  ansible.builtin.template:
    src: "consul-common.j2"
    dest: "{{ consul_config_path | dirname }}/consul.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  notify: restart consul services
  tags:
    - consul-config

- name: place consul server configuration
  ansible.builtin.template:
    src: "consul-server.j2"
    dest: "{{ consul_config_path | dirname }}/server.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  notify: restart consul services
  when: inventory_hostname in groups['consul_servers']
  tags:
    - consul-config

- name: ensure resolved.conf.d directory
  ansible.builtin.file:
    path: "/etc/systemd/resolved.conf.d"
    owner: "root"
    group: "root"
    mode: 0755
    state: directory
  tags:
    - consul-config

- name: configure DNS for Consul
  ansible.builtin.template:
    src: "consul-dns.j2"
    dest: "/etc/systemd/resolved.conf.d/consul.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: restart systemd-resolved
  when:
    - ansible_facts['service_mgr'] == 'systemd'

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
