- name: create systemd unit
  ansible.builtin.template:
    src: vault-systemd.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0644
  notify: systemd_reload
  tags:
    - vault-config

- name: place vault configuration
  ansible.builtin.template:
    src: vault-config.j2
    dest: "{{ vault_config_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0640
  notify: restart vault services
  tags:
    - vault-config

- name: place vault env in profiles
  ansible.builtin.template:
    src: vault-env-profile.j2
    dest: "/etc/profile.d/vault.sh"
    owner: "root"
    group: "root"
    mode: 0755
  tags:
    - vault-config

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
