---
- name: preparing for vault upgrade
  block:
    - name: get service status
      ansible.builtin.service_facts:
      register: services_state

    - name: testing variable vault_version to be installed
      ansible.builtin.debug:
        var: services_state.ansible_facts.services

    - name: stop vault service
      ansible.builtin.systemd:
        name: vault.service
        state: stop
      when:
        - "'vault' in services_state.ansible_facts.services"
        - services_state.ansible_facts.services["vault.service"].state == "running"
  when:
    - vault_systemd.stat.exists
    - vault_binary.stat.exists
  tags:
    - vault-install

- name: remove current binary if it exists
  ansible.builtin.file:
    path: "{{ hashi_binary_dir }}/vault"
    state: absent
  when: vault_binary.stat.exists
  tags:
    - vault-install

- name: download binary archive
  ansible.builtin.get_url:
    url: "{{ vault_archive_url }}/vault_{{ vault_version }}_{% if ansible_facts['architecture'] == 'aarch64' %}linux_arm64{% else %}linux_amd64{% endif %}.zip"
    dest: /tmp/vault-v{{ vault_version }}.zip
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
    checksum: "sha256:{{ vault_archive_url }}/vault_{{ vault_version }}_SHA256SUMS"
  tags:
    - vault-install

- name: test for archive
  ansible.builtin.stat:
    path: /tmp/vault-v{{ vault_version }}.zip
  register: vault_archive_dl
  tags:
    - vault-install

- name: testing variable vault_archive_dl
  ansible.builtin.debug:
    var: vault_archive_dl
  when: vault_install_debug
  tags:
    - vault-install

- name: unpack archive
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/vault-v{{ vault_version }}.zip
    dest: "{{ hashi_binary_dir }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"
  tags:
    - vault-install

- name: remove downloaded archive if it still exists
  ansible.builtin.file:
    path: /tmp/vault-v{{ vault_version }}.zip
    state: absent
  when: vault_archive_dl.stat.exists
  tags:
    - vault-install

- name: set binary capabilities
  community.general.capabilities:
    path: "{{ hashi_binary_dir }}/vault"
    capability: "cap_ipc_lock=ep"
    state: present
  tags:
    - vault-install

- name: create symbolic link for vault
  ansible.builtin.file:
    src: "{{ hashi_binary_dir }}/vault"
    dest: "/usr/local/bin/vault"
    state: link
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
  when:
    - hashi_binary_dir != "/usr/local/bin"
    - not vault_binary_link.stat.exists
  tags:
    - vault-install
