- name: show _vault_certs
  ansible.builtin.debug:
    var: _vault_certs
  when: vault_install_debug
  tags:
    - vault-certs

- name: is there a cluster key in _vault_certs?
  ansible.builtin.debug:
    var: _vault_certs.cluster is defined
  when: vault_install_debug
  tags:
    - vault-certs

- name: is there a cluster key in _vault_certs?
  ansible.builtin.debug:
    var: _vault_certs['cluster'] is defined
  when: vault_install_debug
  tags:
    - vault-certs

- name: is there a client key in _vault_certs?
  ansible.builtin.debug:
    var: _vault_certs.client is defined
  when: vault_install_debug
  tags:
    - vault-certs

- name: is there a client key in _vault_certs?
  ansible.builtin.debug:
    var: _vault_certs['client'] is defined
  when: vault_install_debug
  tags:
    - vault-certs

- name: show _vault_ca
  ansible.builtin.debug:
    var: _vault_ca
  when: vault_install_debug
  tags:
    - vault-certs

- name: show install_certbot
  ansible.builtin.debug:
    var: install_certbot
  when: vault_install_debug
  tags:
    - vault-certs

- name: show use_certbot_cert
  ansible.builtin.debug:
    var: use_certbot_cert
  when: vault_install_debug
  tags:
    - vault-certs

- name: copy certbot certs
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0400
  loop:
    - src: "/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem"
      dest: "{{ vault_config_path | dirname }}/certs/client/chain.pem"
    - src: "/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem"
      dest: "{{ vault_config_path | dirname }}/certs/client/privkey.pem"
  when: use_certbot_cert and install_certbot
  notify: "restart vault services"
  tags:
    - vault-certs

- name: show use_certbot_cert
  ansible.builtin.debug:
    var: _vault_certs['cluster'] | dict2items
  when: vault_install_debug
  loop:
    - "{{ _vault_certs['cluster'] }}"
  tags:
    - vault-certs

- name: write out vault node cluster cert and key
  ansible.builtin.copy:
    content: "{{ item.value.cert }}"
    dest: "{{ vault_config_path | dirname }}/certs/cluster/{{ item.value.filename }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0400
  loop: "{{ _vault_certs['cluster'] | dict2items }}"
  when: _vault_certs.cluster is defined and _vault_certs['cluster'].keys()|length > 0
  notify: "restart vault services"
  tags:
    - vault-certs

- name: write out vault node client cert and key
  ansible.builtin.copy:
    content: "{{ item.value.cert }}"
    dest: "{{ vault_config_path | dirname }}/certs/client/{{ item.value.filename }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0400
  loop: "{{ _vault_certs['client'] | dict2items }}"
  when: _vault_certs.client is defined and _vault_certs['client'].keys()|length > 0
  notify: "restart vault services"
  tags:
    - vault-certs

- name: write out vault ca
  ansible.builtin.copy:
    content: "{{ _vault_ca['pub'] }}"
    dest: "{{ vault_config_path | dirname }}/certs/vault_ca.pem"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0400
  when: _vault_ca.keys()|length > 0
  notify: "restart vault services"
  tags:
    - vault-certs

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
