---
# defaults file for vault_install
_install_vault: false

vault_install_debug: false
hashi_binary_dir: "/usr/local/bin"

vault_install_override: false

vault_version: "1.8.5"
vault_user: "vault"
vault_group: "hashi"
vault_install_dependencies: ["unzip"]

vault_config_path: "/opt/vault/vault.hcl"
vault_archive_url: "https://releases.hashicorp.com/vault/{{ vault_version }}"
vault_dirs:
  - dir: "{{ hashi_binary_dir }}"
    owner: "root"
    group: "root"
  - dir: "{{ vault_config_path | dirname }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  - dir: "{{ vault_config_path | dirname }}/data"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  - dir: "{{ vault_config_path | dirname }}/certs"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  - dir: "{{ vault_config_path | dirname }}/certs/cluster"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  - dir: "{{ vault_config_path | dirname }}/certs/client"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

## Vault configuration variables

vault_listener_port: 8200
vault_cluster_port: 8201
vault_listener_interface: "default"
vault_datacenter: "dc1"

vault_storage: "raft"
vault_ui: true
