---
# defaults file for consul_install
_install_consul: false
use_certbot_cert: false

consul_install_debug: false
hashi_binary_dir: "/usr/local/bin"

consul_install_override: false

consul_version: "1.10.4"
consul_user: "consul"
consul_group: "consul"
consul_install_dependencies: ["unzip"]

consul_config_path: "/opt/consul/consul.hcl"
consul_archive_url: "https://releases.hashicorp.com/consul/{{ consul_version }}"
consul_dirs:
  - dir: "{{ hashi_binary_dir }}"
    owner: "root"
    group: "root"
  - dir: "{{ consul_config_path | dirname }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  - dir: "{{ consul_config_path | dirname }}/data"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  - dir: "{{ consul_config_path | dirname }}/certs"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  - dir: "{{ consul_config_path | dirname }}/certs/cluster"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  - dir: "{{ consul_config_path | dirname }}/certs/client"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

## consul configuration variables

consul_enable_syslog: false
consul_enable_ui: true

consul_datacenter: "dc1"
consul_domain: "consul."
consul_log_level: "info"
consul_alt_domain: ""
consul_ports:
  dns: 8600
  http: 8500
  https: 8501
  grpc: 8502
  lan_serf: 8301
  wan_serf: 8302
  server: 8300

consul_listener_interface: "default"
