---
_arch_lookup:
  amd64:
    arch: amd64
    suffix: "-amd64"
  x86_64:
    arch: amd64
    suffix: "-amd64"
  arm64:
    arch: arm64
    suffix: "-arm64"
  aarch64:
    arch: arm64
    suffix: "-arm64"
  arm:
    arch: arm
    suffix: "-armhf"
  arm6l:
    arch: arm
    suffix: "-armhf"
  armv6l:
    arch: arm
    suffix: "-armhf"
  arm7:
    arch: arm
    suffix: "-armhf"
  armv7l:
    arch: arm
    suffix: "-armhf"
  armhf:
    arch: arm
    suffix: "-armhf"

# defaults file for consul_install

hashi_binary_dir: "/usr/local/bin"

consul_version: "1.11.4"
consul_user: "consul"
consul_group: "hashi"
consul_install_dependencies: ["unzip"]

consul_config_path: "/opt/consul/consul.hcl"
consul_archive_url: "https://releases.hashicorp.com/consul/{{ consul_version }}"
consul_dirs:
  - dir: "{{ hashi_binary_dir }}"
    owner: "root"
    group: "root"
  - dir: "{{ consul_config_path | dirname }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  - dir: "{{ consul_config_path | dirname }}/data"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  - dir: "{{ consul_config_path | dirname }}/certs"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  - dir: "{{ consul_config_path | dirname }}/certs/cluster"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  - dir: "{{ consul_config_path | dirname }}/certs/client"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

## consul configuration variables

consul_enable_syslog: false
consul_enable_ui: true

consul_datacenter: "dc1"
consul_domain: "consul."
consul_log_level: "info"
consul_alt_domain: ""
consul_ports:
  dns: 8600
  http: 8500
  https: 8501
  grpc: 8502
  lan_serf: 8301
  wan_serf: 8302
  server: 8300

consul_recursors: ["1.1.1.1", "8.8.8.8"]

consul_listener_interface: "default"

## consul template variables

ct_version: "0.27.2"
ct_archive: "https://releases.hashicorp.com/consul-template"

ct_config_dir: "/opt/consul-template.d"
ct_env_path: "/etc/default/consul-template"
ct_env: {}
