---
ansible_user: ubuntu

install_ddclient: true
install_certbot: true

kernel_modules:
  - "br_netfilter"

print_terraform_backend: false

consul_datacenter: "{{ _olympus_v2['consul_hosts']['datacenter'] }}"
nomad_datacenter: "{{ _olympus_v2['nomad_hosts']['datacenter'] }}"

hostprep_install_dependencies:
  - "cpu-checker"
  - "qemu"
  - "qemu-kvm"
  - "libvirt-daemon"
  - "libvirt-clients"
  - "bridge-utils"
  - "openjdk-17-jdk-headless"
  - "slirp4netns"
  - "fuse-overlayfs"
  - "lldpd"
  - "tmux"

nomad_drivers:
  raw_exec: true
  podman: false
  containerd: false
  docker: true

cni:
  url: "https://github.com/containernetworking/plugins/releases/download/"
  version: "1.0.1"
