---
ansible_user: ubuntu

install_ddclient: true
install_certbot: true

print_terraform_backend: false

consul_datacenter: "{{ _olympus_v2['consul_hosts']['datacenter'] }}"
nomad_datacenter: "{{ _olympus_v2['nomad_hosts']['datacenter'] }}"
