---
- name: fact and backend gathering
  hosts: k3s_cluster
  gather_facts: true
  become: true
  handlers:
    - name: import handlers
      ansible.builtin.import_tasks: ./handlers/main.yml
  roles:
    - role: xanmanning.k3s
      vars:
        k3s_become: true
        k3s_skip_validation: false
        k3s_skip_env_checks: false
        k3s_install_hard_links: false

        k3s_registration_address: "https://{{ k3s_registration_vip }}:6443"
        k3s_service_after: []
        k3s_service_env_file: false

        k3s_server:
          datastore-endpoint: "postgres://{{ vault_postgres_user }}:{{ vault_postgres_pass }}@qnap.nwlnexus.net:5432/k3sdb"
          cluster-cidr: "172.20.0.0/16"
          service-cidr: "172.21.0.0/16"
          cluster-dns: "{{ k3s_server['service-cidr'] | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr('10') | ansible.netcommon.ipaddr('host') }}"
          flannel-backend: "wireguard"
          tls_san: "{{ k3s_registration_vip }}"
          token: "{{ _olympus_v2['k3s_cluster']['cluster_token'] }}"

        k3s_agent:
          token: "{{ _olympus_v2['k3s_cluster']['cluster_token'] }}"
          with-node-id: true

        k3s_server_manifests_urls: []
        k3s_server_pod_manifests_urls: []
      when:
        - use_k3s
        - "'k3s_cluster' in group_names"
      tags: k3s-install
