---
# handlers file for ddclient_install
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart ddclient
  ansible.builtin.systemd:
    daemon_reload: true
    name: ddclient.service
    state: restarted
    enabled: true
  listen:
    - "restart ddclient service"
