_cluster:
  vault:
    install: true
    version: latest
    service:
      enabled: false
      masked: false
      user: vault
    config: {}

cluster_merged: "{{ _cluster|combine(cluster, recursive=true) }}"

_dns:
  forward: false
  target_port: "8600"

dns_merged: "{{ _dns|combine(dns, recursive=true) }}"
