consul_install_debug: true
consul_install_override: false
consul_version: 1.10.4

# This is not required as the default interface for these devices is eth0 but this is here
# to show the possible customization and testing. Defining an invalid interface will cause
# the play to fail.
consul_listener_interface: "eth0"
consul_listener_port: 8200
