---
# tasks file for certbot_install
- name: ensure apt repository is removed
  ansible.builtin.apt_repository:
    repo: "ppa:certbot/certbot"
    state: absent

- name: install certbot
  community.general.snap:
    name: certbot
    classic: true

- name: enable plugins
  ansible.builtin.command: snap set certbot trust-plugin-with-root=ok
  register: certbot_output
  changed_when: false

- name: create symbolic link for certbot
  ansible.builtin.file:
    src: "/snap/bin/certbot"
    dest: "/usr/bin/certbot"
    state: link

- name: register account
  ansible.builtin.command:
    cmd: /usr/bin/certbot register --email {{ cf_email }} --no-eff-email --agree-tos
    creates: /etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org

- name: place certbot ini dir for dns plugins
  ansible.builtin.file:
    path: "{{ certbot_ini_dir }}"
    mode: "0644"
    state: directory

- name: configure deploy_renewal_hooks
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/certbot/{{ item }}.j2"
    dest: "/etc/letsencrypt/renewal-hooks/deploy/{{ item }}.sh"
    owner: "root"
    group: "root"
    mode: "750"
  loop: "{{ _deploy_renewal_hooks }}"
  when: _deploy_renewal_hooks|length > 0

- name: configure pre_renewal_hooks
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/certbot/{{ item }}.j2"
    dest: "/etc/letsencrypt/renewal-hooks/pre/{{ item }}.sh"
    owner: "root"
    group: "root"
    mode: "750"
  loop: "{{ _pre_renewal_hooks }}"
  when: _pre_renewal_hooks|length > 0

- name: configure post_renewal_hooks
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/certbot/{{ item }}.j2"
    dest: "/etc/letsencrypt/renewal-hooks/post/{{ item }}.sh"
    owner: "root"
    group: "root"
    mode: "750"
  loop: "{{ _post_renewal_hooks }}"
  when: _post_renewal_hooks|length > 0

- name: use cloudflare dns plugin
  block:
    - name: install certbot cloudflare plugin
      community.general.snap:
        name: certbot-dns-cloudflare

    - name: place cloudflare dns credentials file
      ansible.builtin.template:
        src: "certbot_dns.j2"
        dest: "{{ certbot_ini_dir }}/cf-creds.ini"
        mode: 0600

    - name: request and register cert
      ansible.builtin.command:
        cmd: /usr/bin/certbot certonly --dns-cloudflare --dns-cloudflare-credentials {{ certbot_ini_dir }}/cf-creds.ini -d {{ inventory_hostname }}
        creates: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
  when: dns_plugin == "cloudflare"
